# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/uuid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='type/uuid.proto',
  package='inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftype/uuid.proto\x12\tinventory\"\x15\n\x04uuid\x12\r\n\x05value\x18\x01 \x01(\tb\x06proto3')
)




_UUID = _descriptor.Descriptor(
  name='uuid',
  full_name='inventory.uuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='inventory.uuid.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['uuid'] = _UUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

uuid = _reflection.GeneratedProtocolMessageType('uuid', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'type.uuid_pb2'
  # @@protoc_insertion_point(class_scope:inventory.uuid)
  })
_sym_db.RegisterMessage(uuid)


# @@protoc_insertion_point(module_scope)
