# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bound_item_pb2 as bound__item__pb2


class BoundItemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetBoundItem = channel.unary_unary(
        '/inventory.BoundItem/GetBoundItem',
        request_serializer=bound__item__pb2.BoundItemRequest.SerializeToString,
        response_deserializer=bound__item__pb2.BoundItemResponse.FromString,
        )
    self.GetBoundItems = channel.unary_stream(
        '/inventory.BoundItem/GetBoundItems',
        request_serializer=bound__item__pb2.BoundItemRequest.SerializeToString,
        response_deserializer=bound__item__pb2.BoundItemResponse.FromString,
        )


class BoundItemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetBoundItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBoundItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BoundItemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetBoundItem': grpc.unary_unary_rpc_method_handler(
          servicer.GetBoundItem,
          request_deserializer=bound__item__pb2.BoundItemRequest.FromString,
          response_serializer=bound__item__pb2.BoundItemResponse.SerializeToString,
      ),
      'GetBoundItems': grpc.unary_stream_rpc_method_handler(
          servicer.GetBoundItems,
          request_deserializer=bound__item__pb2.BoundItemRequest.FromString,
          response_serializer=bound__item__pb2.BoundItemResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inventory.BoundItem', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
