# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convert_rule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from type import uuid_pb2 as type_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='convert_rule.proto',
  package='inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63onvert_rule.proto\x12\tinventory\x1a\x0ftype/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x12\x43onvertRuleRequest\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.inventory.uuid\x12\x16\n\x0e\x64\x65\x66\x61ult_amount\x18\x02 \x01(\x04\x12\x0e\n\x06status\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xba\x01\n\x13\x43onvertRuleResponse\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.inventory.uuid\x12\x16\n\x0e\x64\x65\x66\x61ult_amount\x18\x02 \x01(\x04\x12\x0e\n\x06status\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb4\x01\n\x0b\x43onvertRule\x12Q\n\x0eGetConvertRule\x12\x1d.inventory.ConvertRuleRequest\x1a\x1e.inventory.ConvertRuleResponse\"\x00\x12R\n\x0fGetConvertRules\x12\x1d.inventory.ConvertRuleRequest\x1a\x1e.inventory.ConvertRuleResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[type_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CONVERTRULEREQUEST = _descriptor.Descriptor(
  name='ConvertRuleRequest',
  full_name='inventory.ConvertRuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='inventory.ConvertRuleRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_amount', full_name='inventory.ConvertRuleRequest.default_amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inventory.ConvertRuleRequest.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='inventory.ConvertRuleRequest.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='inventory.ConvertRuleRequest.updated_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=269,
)


_CONVERTRULERESPONSE = _descriptor.Descriptor(
  name='ConvertRuleResponse',
  full_name='inventory.ConvertRuleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='inventory.ConvertRuleResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_amount', full_name='inventory.ConvertRuleResponse.default_amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inventory.ConvertRuleResponse.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='inventory.ConvertRuleResponse.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='inventory.ConvertRuleResponse.updated_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=458,
)

_CONVERTRULEREQUEST.fields_by_name['id'].message_type = type_dot_uuid__pb2._UUID
_CONVERTRULEREQUEST.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONVERTRULEREQUEST.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONVERTRULERESPONSE.fields_by_name['id'].message_type = type_dot_uuid__pb2._UUID
_CONVERTRULERESPONSE.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONVERTRULERESPONSE.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ConvertRuleRequest'] = _CONVERTRULEREQUEST
DESCRIPTOR.message_types_by_name['ConvertRuleResponse'] = _CONVERTRULERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConvertRuleRequest = _reflection.GeneratedProtocolMessageType('ConvertRuleRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTRULEREQUEST,
  '__module__' : 'convert_rule_pb2'
  # @@protoc_insertion_point(class_scope:inventory.ConvertRuleRequest)
  })
_sym_db.RegisterMessage(ConvertRuleRequest)

ConvertRuleResponse = _reflection.GeneratedProtocolMessageType('ConvertRuleResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTRULERESPONSE,
  '__module__' : 'convert_rule_pb2'
  # @@protoc_insertion_point(class_scope:inventory.ConvertRuleResponse)
  })
_sym_db.RegisterMessage(ConvertRuleResponse)



_CONVERTRULE = _descriptor.ServiceDescriptor(
  name='ConvertRule',
  full_name='inventory.ConvertRule',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=461,
  serialized_end=641,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConvertRule',
    full_name='inventory.ConvertRule.GetConvertRule',
    index=0,
    containing_service=None,
    input_type=_CONVERTRULEREQUEST,
    output_type=_CONVERTRULERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetConvertRules',
    full_name='inventory.ConvertRule.GetConvertRules',
    index=1,
    containing_service=None,
    input_type=_CONVERTRULEREQUEST,
    output_type=_CONVERTRULERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERTRULE)

DESCRIPTOR.services_by_name['ConvertRule'] = _CONVERTRULE

# @@protoc_insertion_point(module_scope)
