# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_serial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from type import uuid_pb2 as type_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='item_serial.proto',
  package='inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11item_serial.proto\x12\tinventory\x1a\x0ftype/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n\x11ItemSerialRequest\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.inventory.uuid\x12\x0e\n\x06status\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa1\x01\n\x12ItemSerialResponse\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.inventory.uuid\x12\x0e\n\x06status\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xaf\x01\n\nItemSerial\x12N\n\rGetItemSerial\x12\x1c.inventory.ItemSerialRequest\x1a\x1d.inventory.ItemSerialResponse\"\x00\x12Q\n\x0eGetItemSerials\x12\x1c.inventory.ItemSerialRequest\x1a\x1d.inventory.ItemSerialResponse\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[type_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ITEMSERIALREQUEST = _descriptor.Descriptor(
  name='ItemSerialRequest',
  full_name='inventory.ItemSerialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='inventory.ItemSerialRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inventory.ItemSerialRequest.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='inventory.ItemSerialRequest.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='inventory.ItemSerialRequest.updated_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=243,
)


_ITEMSERIALRESPONSE = _descriptor.Descriptor(
  name='ItemSerialResponse',
  full_name='inventory.ItemSerialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='inventory.ItemSerialResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inventory.ItemSerialResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='inventory.ItemSerialResponse.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='inventory.ItemSerialResponse.updated_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=407,
)

_ITEMSERIALREQUEST.fields_by_name['id'].message_type = type_dot_uuid__pb2._UUID
_ITEMSERIALREQUEST.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ITEMSERIALREQUEST.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ITEMSERIALRESPONSE.fields_by_name['id'].message_type = type_dot_uuid__pb2._UUID
_ITEMSERIALRESPONSE.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ITEMSERIALRESPONSE.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ItemSerialRequest'] = _ITEMSERIALREQUEST
DESCRIPTOR.message_types_by_name['ItemSerialResponse'] = _ITEMSERIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemSerialRequest = _reflection.GeneratedProtocolMessageType('ItemSerialRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSERIALREQUEST,
  '__module__' : 'item_serial_pb2'
  # @@protoc_insertion_point(class_scope:inventory.ItemSerialRequest)
  })
_sym_db.RegisterMessage(ItemSerialRequest)

ItemSerialResponse = _reflection.GeneratedProtocolMessageType('ItemSerialResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSERIALRESPONSE,
  '__module__' : 'item_serial_pb2'
  # @@protoc_insertion_point(class_scope:inventory.ItemSerialResponse)
  })
_sym_db.RegisterMessage(ItemSerialResponse)



_ITEMSERIAL = _descriptor.ServiceDescriptor(
  name='ItemSerial',
  full_name='inventory.ItemSerial',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=410,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetItemSerial',
    full_name='inventory.ItemSerial.GetItemSerial',
    index=0,
    containing_service=None,
    input_type=_ITEMSERIALREQUEST,
    output_type=_ITEMSERIALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetItemSerials',
    full_name='inventory.ItemSerial.GetItemSerials',
    index=1,
    containing_service=None,
    input_type=_ITEMSERIALREQUEST,
    output_type=_ITEMSERIALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMSERIAL)

DESCRIPTOR.services_by_name['ItemSerial'] = _ITEMSERIAL

# @@protoc_insertion_point(module_scope)
