# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import item_pb2 as item__pb2


class ItemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetItem = channel.unary_unary(
        '/inventory.Item/GetItem',
        request_serializer=item__pb2.ItemRequest.SerializeToString,
        response_deserializer=item__pb2.ItemResponse.FromString,
        )
    self.GetItems = channel.unary_stream(
        '/inventory.Item/GetItems',
        request_serializer=item__pb2.ItemRequest.SerializeToString,
        response_deserializer=item__pb2.ItemResponse.FromString,
        )


class ItemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ItemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetItem': grpc.unary_unary_rpc_method_handler(
          servicer.GetItem,
          request_deserializer=item__pb2.ItemRequest.FromString,
          response_serializer=item__pb2.ItemResponse.SerializeToString,
      ),
      'GetItems': grpc.unary_stream_rpc_method_handler(
          servicer.GetItems,
          request_deserializer=item__pb2.ItemRequest.FromString,
          response_serializer=item__pb2.ItemResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inventory.Item', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
