# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import item_serial_pb2 as item__serial__pb2


class ItemSerialStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetItemSerial = channel.unary_unary(
        '/inventory.ItemSerial/GetItemSerial',
        request_serializer=item__serial__pb2.ItemSerialRequest.SerializeToString,
        response_deserializer=item__serial__pb2.ItemSerialResponse.FromString,
        )
    self.GetItemSerials = channel.unary_stream(
        '/inventory.ItemSerial/GetItemSerials',
        request_serializer=item__serial__pb2.ItemSerialRequest.SerializeToString,
        response_deserializer=item__serial__pb2.ItemSerialResponse.FromString,
        )


class ItemSerialServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetItemSerial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetItemSerials(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ItemSerialServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetItemSerial': grpc.unary_unary_rpc_method_handler(
          servicer.GetItemSerial,
          request_deserializer=item__serial__pb2.ItemSerialRequest.FromString,
          response_serializer=item__serial__pb2.ItemSerialResponse.SerializeToString,
      ),
      'GetItemSerials': grpc.unary_stream_rpc_method_handler(
          servicer.GetItemSerials,
          request_deserializer=item__serial__pb2.ItemSerialRequest.FromString,
          response_serializer=item__serial__pb2.ItemSerialResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inventory.ItemSerial', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
