# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import location_pb2 as location__pb2


class LocationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLocation = channel.unary_unary(
        '/inventory.Location/GetLocation',
        request_serializer=location__pb2.LocationRequest.SerializeToString,
        response_deserializer=location__pb2.LocationResponse.FromString,
        )
    self.GetLocations = channel.unary_stream(
        '/inventory.Location/GetLocations',
        request_serializer=location__pb2.LocationRequest.SerializeToString,
        response_deserializer=location__pb2.LocationResponse.FromString,
        )


class LocationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLocations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LocationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLocation': grpc.unary_unary_rpc_method_handler(
          servicer.GetLocation,
          request_deserializer=location__pb2.LocationRequest.FromString,
          response_serializer=location__pb2.LocationResponse.SerializeToString,
      ),
      'GetLocations': grpc.unary_stream_rpc_method_handler(
          servicer.GetLocations,
          request_deserializer=location__pb2.LocationRequest.FromString,
          response_serializer=location__pb2.LocationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inventory.Location', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
